spring:
  application:
    name: roulette-api
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      format_sql: true
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/splitthefeatures-roulette-api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hibernate:
  temp:
    use_jdbc_metadata_defaults: false

api:
  cors:
    enabled: true

server:
  port: 8082

logging:
  level: DEBUG
  level.org.hibernate.SQL: DEBUG

roulette:
  discount:
    min: 5
    max: 20
    possibilities-for-max: 10